### ISSUE TITLE
ssh scheduling hangs, doesn't run jobs.

### ISSUE THREAD

**Issue by dshayden** [erdewit/distex#5]
ssh causes output on the terminal as if I had ran ssh -T hostname myself, and hangs there, not actually scheduling jobs. Replacing distex's ssh -T arg with -t -t appears to work for setting up the connection, but then I get a permission denied error for socket connection. Stack trace for when I replace -T with -t -t below. Setup works fine if I manually run python -m distex.server on each node instead of ssh. Ubuntu 16.04 for host and nodes, latest 0.5.4 distex. Python 3.6.1. Remote machines have appropriate keys for password-less ssh.

```
Traceback (most recent call last):
  File "/.../anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/.../anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/rvsn/vp/projects/edu/distex/distex/processor.py", line 116, in <module>
    processor = Processor(args.host, args.port, args.unix_path, loop=loop)
  File "/data/rvsn/vp/projects/edu/distex/distex/processor.py", line 30, in __init__
    loop.run_until_complete(self.create())
  File "/.../anaconda3/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/data/rvsn/vp/projects/edu/distex/distex/processor.py", line 35, in create
    lambda: self, self._unix_path)
  File "/.../anaconda3/lib/python3.6/asyncio/unix_events.py", line 236, in create_unix_connection
    yield from self.sock_connect(sock, path)
  File "/.../anaconda3/lib/python3.6/asyncio/selector_events.py", line 451, in sock_connect
    return (yield from fut)
  File "/.../anaconda3/lib/python3.6/asyncio/selector_events.py", line 456, in _sock_connect
    sock.connect(address)
PermissionError: [Errno 13] Permission denied
Task was destroyed but it is pending!
task: <Task pending coro=<Processor.worker() running at /data/rvsn/vp/projects/edu/distex/distex/processor.py:42> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fa3f3833dc8>()]>>
Traceback (most recent call last):
  File "/.../anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/.../anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/rvsn/vp/projects/edu/distex/distex/processor.py", line 116, in <module>
    processor = Processor(args.host, args.port, args.unix_path, loop=loop)
  File "/data/rvsn/vp/projects/edu/distex/distex/processor.py", line 30, in __init__
    loop.run_until_complete(self.create())
  File "/.../anaconda3/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/data/rvsn/vp/projects/edu/distex/distex/processor.py", line 35, in create
    lambda: self, self._unix_path)
  File "/.../anaconda3/lib/python3.6/asyncio/unix_events.py", line 236, in create_unix_connection
    yield from self.sock_connect(sock, path)
  File "/.../anaconda3/lib/python3.6/asyncio/selector_events.py", line 451, in sock_connect
    return (yield from fut)
  File "/.../anaconda3/lib/python3.6/asyncio/selector_events.py", line 456, in _sock_connect
    sock.connect(address)
PermissionError: [Errno 13] Permission denied
Task was destroyed but it is pending!
task: <Task pending coro=<Processor.worker() running at /.../distex/processor.py:42> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f669d0dbdc8>()]>>
```

**Comment by erdewit** [comment]
On Ubuntu 17.10 or Fedora 27 I can't reproduce the issue. The only way I can get it to hang is if one of the remote machines is not running a SSH server.

According to the stack trace a worker process is denied access to the Unix domain socket, which is a /tmp/distex-* file which should have the proper permissions for the worker process to access it. Perhaps there is something that could interfere with these permissions, like selinux being active.

**Comment by erdewit** [comment]
It turns out that the issue was that python3 on Ubuntu 16.04 resolves to python3.5, while Python >= 3.6 is needed.

The code has been adjusted to use sys.executable instead of hardcoding python3; The assumption being that the Python installation on the remote hosts will be the same as on the local one.
